/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  mySidebar: [
    {
      type: 'category',
      label: 'TiDB in Kubernetes',
      link: {type: 'doc', id: 'index'},
      items : [
          {
              type: 'doc',
              label: 'TiDB Operator',
              id: 'tidb-operator-overview',
          },
          {
              type: 'doc',
              label: 'What\'s New in v1.3',
              id: 'whats-new-in-v1.3',
          }
    ]
    },
    {
        type: 'doc',
        label: 'Getting Started',
        id: 'get-started',
    },
    {
        type: 'category',
        label: 'Deploy',
        items: [
            {
                type: 'category',
                label: 'In Self-Managed Kubernetes',
                items: [
                    'prerequisites',
                    'configure-storage-class',
                    'deploy-tidb-operator',
                    'configure-a-tidb-cluster',
                    'deploy-on-general-kubernetes',
                    'initialize-a-cluster',
                    'access-tidb'
                ]
            },
            {
                type: 'category',
                label: 'In Public Cloud Kubernetes',
                items: [
                    'deploy-on-aws-eks',
                    'deploy-on-gcp-gke',
                    'deploy-on-azure-aks',
                    'deploy-on-alibaba-cloud'
                ]
            },
            {
                type: 'doc',
                label: 'On ARM64',
                id: 'deploy-cluster-on-arm64',
            },
            {
                type: 'doc',
                label: 'HTAP',
                id: 'deploy-tiflash',
            },
            {
                type: 'category',
                label: 'Across Multiple Kubernetes Clusters',
                items: [
                    {
                        type: 'doc',
                        label: 'Amazon EKS',
                        id: 'build-multi-aws-eks',
                    },
                    {
                        type: 'doc',
                        label: 'GCP GKE',
                        id: 'build-multi-gcp-gke',
                    },
                    'deploy-tidb-cluster-across-multiple-kubernetes'
                ]
            },
            {
                type: 'doc',
                label: 'Heterogeneous Cluster',
                id: 'deploy-heterogeneous-tidb-cluster',
            },
            {
                type: 'doc',
                label: 'Enterprise Edition',
                id: 'deploy-tidb-enterprise-edition',
            },
            {
                type: 'doc',
                label: 'TiCDC',
                id: 'deploy-ticdc',
            },
            {
                type: 'doc',
                label: 'TiDB Binlog',
                id: 'deploy-tidb-binlog',
            },

        ]
    },
    {
        type: 'category',
        label: 'Migrate',
        items: [
            {
                type: 'doc',
                label: 'Import Data',
                id: 'restore-data-using-tidb-lightning'
            },
            {
                type: 'category',
                label: 'Migrate from MySQL',
                items: [
                    'deploy-tidb-dm',
                    'use-tidb-dm'
                ]
            },
            'migrate-tidb-to-kubernetes'
        ]
    },
    {
        type: 'category',
        label: 'Manage',
        items: [
            {
                type: 'category',
                label: 'Secure',
                items: [
                    'enable-tls-for-mysql-client',
                    'enable-tls-between-components',
                    'enable-tls-for-dm',
                    'enable-tls-for-ticdc-sink',
                    'renew-tls-certificate',
                    'containers-run-as-non-root-user'
                ]
            },
            {
                type: 'doc',
                label: 'Scale',
                id: 'scale-a-tidb-cluster'
            },
            {
                type: 'category',
                label: 'Upgrade',
                items: [
                    'upgrade-a-tidb-cluster',
                    { 'Upgrade TiDB Operator': ['upgrade-tidb-operator','canary-upgrade-tidb-operator']}
                ]
            },
            {
                type: 'category',
                label: 'Backup and Restore',
                link: {type: 'doc', id: 'backup-restore-overview'},
                items: [
                    'grant-permissions-to-remote-storage',
                    {
                        'Amazon S3 Compatible Storage': [
                            'backup-to-aws-s3-using-br',
                            'restore-from-aws-s3-using-br',
                            'backup-to-s3',
                            'restore-from-s3'
                        ]
                    },
                    {
                        'Google Cloud Storage': [
                            'backup-to-gcs-using-br',
                            'restore-from-gcs-using-br',
                            'backup-to-gcs',
                            'restore-from-gcs'
                        ]
                    },
                    {
                        'Persistent Volumes': ['backup-to-pv-using-br','restore-from-pv-using-br']
                    }
                ]
            },
            {
                'Maintain': [
                    'restart-a-tidb-cluster',
                    'destroy-a-tidb-cluster',
                    'view-logs',
                    'modify-tidb-configuration',
                    'use-auto-failover',
                    'pause-sync-of-tidb-cluster',
                    'deploy-multiple-tidb-operator',
                    'maintain-a-kubernetes-node',
                    'migrate-to-helm3'
                ]
            },
            {
                'Monitor and Alert': [
                    'monitor-a-tidb-cluster',
                    'access-dashboard',
                    'aggregate-multiple-cluster-monitor-data',
                    'enable-monitor-dynamic-configuration',
                    'enable-monitor-shards'
                ]
            },
            {
                'Disaster Recovery': [
                    'recover-deleted-cluster',
                    'pd-recover'
                ]
            }
        ]
    },
    {
        'Troubleshoot': [
            'tips',
            'deploy-failures',
            'exceptions',
            'network-issues'
        ]
    },
    'faq',

  ],

  refSidebar: [
      {
          'Architecture': [
            'architecture',
            'tidb-scheduler',
            'advanced-statefulset',
            'enable-admission-webhook',
          ]
      },
      'benchmark-sysbench',
      {
          type: 'link',
          label: 'API References',
          href: 'https://github.com/pingcap/tidb-operator/blob/master/docs/api-references/docs.md'
      },
      'cheat-sheet',
      'tidb-operator-rbac',
      {
          'Tools': ['use-tkctl', 'tidb-toolkit']
      },
      {
          'Configure': ['configure-tidb-binlog-drainer','tidb-cluster-chart-config','configure-backup']
      },
      'logs-collection',
      'monitor-kubernetes'

  ]
};

module.exports = sidebars;
